baseURL = "https://none.one"
# title = "roots"
author = "none"
copyright = "Copyright © 2021, None."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

theme="roots"

enableGitInfo=false
enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"
[pygmentsOptions]
  linenos= true

[markup]
  defaultMarkdownHandler= "goldmark"
